require 'hanabanashiku.plugins.treesitter'
require 'hanabanashiku.plugins.lsp'
require 'hanabanashiku.plugins.neotree'
require 'hanabanashiku.plugins.smartsplits'
require 'hanabanashiku.plugins.dap'
require 'hanabanashiku.plugins.neotest'
require 'hanabanashiku.plugins.lualine'
