require 'hanabanashiku.plugins.telescope'
require 'hanabanashiku.plugins.neotree'
require 'hanabanashiku.plugins.lualine'
require 'hanabanashiku.plugins.smartsplits'
require 'hanabanashiku.plugins.lsp'
require 'hanabanashiku.plugins.lualine'